(cl:defpackage udp_com-srv
  (:use )
  (:export
   "UDPSEND"
   "<UDPSEND-REQUEST>"
   "UDPSEND-REQUEST"
   "<UDPSEND-RESPONSE>"
   "UDPSEND-RESPONSE"
   "UDPSOCKET"
   "<UDPSOCKET-REQUEST>"
   "UDPSOCKET-REQUEST"
   "<UDPSOCKET-RESPONSE>"
   "UDPSOCKET-RESPONSE"
  ))

