// Generated by gencpp from file udp_com/UdpPacket.msg
// DO NOT EDIT!


#ifndef UDP_COM_MESSAGE_UDPPACKET_H
#define UDP_COM_MESSAGE_UDPPACKET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace udp_com
{
template <class ContainerAllocator>
struct UdpPacket_
{
  typedef UdpPacket_<ContainerAllocator> Type;

  UdpPacket_()
    : header()
    , address()
    , srcPort(0)
    , data()  {
    }
  UdpPacket_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , address(_alloc)
    , srcPort(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _address_type;
  _address_type address;

   typedef uint16_t _srcPort_type;
  _srcPort_type srcPort;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::udp_com::UdpPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udp_com::UdpPacket_<ContainerAllocator> const> ConstPtr;

}; // struct UdpPacket_

typedef ::udp_com::UdpPacket_<std::allocator<void> > UdpPacket;

typedef boost::shared_ptr< ::udp_com::UdpPacket > UdpPacketPtr;
typedef boost::shared_ptr< ::udp_com::UdpPacket const> UdpPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udp_com::UdpPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udp_com::UdpPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::udp_com::UdpPacket_<ContainerAllocator1> & lhs, const ::udp_com::UdpPacket_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.address == rhs.address &&
    lhs.srcPort == rhs.srcPort &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::udp_com::UdpPacket_<ContainerAllocator1> & lhs, const ::udp_com::UdpPacket_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace udp_com

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::udp_com::UdpPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udp_com::UdpPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udp_com::UdpPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udp_com::UdpPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udp_com::UdpPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udp_com::UdpPacket_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udp_com::UdpPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8198692589ba27213e2e7991f4492e00";
  }

  static const char* value(const ::udp_com::UdpPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8198692589ba2721ULL;
  static const uint64_t static_value2 = 0x3e2e7991f4492e00ULL;
};

template<class ContainerAllocator>
struct DataType< ::udp_com::UdpPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udp_com/UdpPacket";
  }

  static const char* value(const ::udp_com::UdpPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udp_com::UdpPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string address\n"
"uint16 srcPort\n"
"uint8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::udp_com::UdpPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udp_com::UdpPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.address);
      stream.next(m.srcPort);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UdpPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udp_com::UdpPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udp_com::UdpPacket_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.address);
    s << indent << "srcPort: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.srcPort);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDP_COM_MESSAGE_UDPPACKET_H
