// Generated by gencpp from file udp_com/UdpSocketResponse.msg
// DO NOT EDIT!


#ifndef UDP_COM_MESSAGE_UDPSOCKETRESPONSE_H
#define UDP_COM_MESSAGE_UDPSOCKETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udp_com
{
template <class ContainerAllocator>
struct UdpSocketResponse_
{
  typedef UdpSocketResponse_<ContainerAllocator> Type;

  UdpSocketResponse_()
    : successful(false)  {
    }
  UdpSocketResponse_(const ContainerAllocator& _alloc)
    : successful(false)  {
  (void)_alloc;
    }



   typedef uint8_t _successful_type;
  _successful_type successful;





  typedef boost::shared_ptr< ::udp_com::UdpSocketResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udp_com::UdpSocketResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UdpSocketResponse_

typedef ::udp_com::UdpSocketResponse_<std::allocator<void> > UdpSocketResponse;

typedef boost::shared_ptr< ::udp_com::UdpSocketResponse > UdpSocketResponsePtr;
typedef boost::shared_ptr< ::udp_com::UdpSocketResponse const> UdpSocketResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udp_com::UdpSocketResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udp_com::UdpSocketResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::udp_com::UdpSocketResponse_<ContainerAllocator1> & lhs, const ::udp_com::UdpSocketResponse_<ContainerAllocator2> & rhs)
{
  return lhs.successful == rhs.successful;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::udp_com::UdpSocketResponse_<ContainerAllocator1> & lhs, const ::udp_com::UdpSocketResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace udp_com

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udp_com::UdpSocketResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udp_com::UdpSocketResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udp_com::UdpSocketResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ccdb752b565be6d250259ff3d0c7ea1";
  }

  static const char* value(const ::udp_com::UdpSocketResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ccdb752b565be6dULL;
  static const uint64_t static_value2 = 0x250259ff3d0c7ea1ULL;
};

template<class ContainerAllocator>
struct DataType< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udp_com/UdpSocketResponse";
  }

  static const char* value(const ::udp_com::UdpSocketResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool successful\n"
"\n"
;
  }

  static const char* value(const ::udp_com::UdpSocketResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.successful);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UdpSocketResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udp_com::UdpSocketResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udp_com::UdpSocketResponse_<ContainerAllocator>& v)
  {
    s << indent << "successful: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.successful);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDP_COM_MESSAGE_UDPSOCKETRESPONSE_H
