// Generated by gencpp from file udp_com/UdpSocket.msg
// DO NOT EDIT!


#ifndef UDP_COM_MESSAGE_UDPSOCKET_H
#define UDP_COM_MESSAGE_UDPSOCKET_H

#include <ros/service_traits.h>


#include <udp_com/UdpSocketRequest.h>
#include <udp_com/UdpSocketResponse.h>


namespace udp_com
{

struct UdpSocket
{

typedef UdpSocketRequest Request;
typedef UdpSocketResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UdpSocket
} // namespace udp_com


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::udp_com::UdpSocket > {
  static const char* value()
  {
    return "1f9ba3aa4d7a9f81e5e4af8aceccdf35";
  }

  static const char* value(const ::udp_com::UdpSocket&) { return value(); }
};

template<>
struct DataType< ::udp_com::UdpSocket > {
  static const char* value()
  {
    return "udp_com/UdpSocket";
  }

  static const char* value(const ::udp_com::UdpSocket&) { return value(); }
};


// service_traits::MD5Sum< ::udp_com::UdpSocketRequest> should match
// service_traits::MD5Sum< ::udp_com::UdpSocket >
template<>
struct MD5Sum< ::udp_com::UdpSocketRequest>
{
  static const char* value()
  {
    return MD5Sum< ::udp_com::UdpSocket >::value();
  }
  static const char* value(const ::udp_com::UdpSocketRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::udp_com::UdpSocketRequest> should match
// service_traits::DataType< ::udp_com::UdpSocket >
template<>
struct DataType< ::udp_com::UdpSocketRequest>
{
  static const char* value()
  {
    return DataType< ::udp_com::UdpSocket >::value();
  }
  static const char* value(const ::udp_com::UdpSocketRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::udp_com::UdpSocketResponse> should match
// service_traits::MD5Sum< ::udp_com::UdpSocket >
template<>
struct MD5Sum< ::udp_com::UdpSocketResponse>
{
  static const char* value()
  {
    return MD5Sum< ::udp_com::UdpSocket >::value();
  }
  static const char* value(const ::udp_com::UdpSocketResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::udp_com::UdpSocketResponse> should match
// service_traits::DataType< ::udp_com::UdpSocket >
template<>
struct DataType< ::udp_com::UdpSocketResponse>
{
  static const char* value()
  {
    return DataType< ::udp_com::UdpSocket >::value();
  }
  static const char* value(const ::udp_com::UdpSocketResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UDP_COM_MESSAGE_UDPSOCKET_H
